### ISSUE TITLE
为啥开始执行log不是立即执行？

### ISSUE THREAD

**Issue by hanxiaofeng** [iqiyi/TaskManager#2]
new IdleTask("task1") {
                    @Override
                    public void doTask() {
                        Log.e("test", "" + getName() + "-----------开始执行");
                        try {
                            Thread.sleep(5000);
                            Log.e("test", "" + getName() + "-----------执行完毕----");
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }.postAsync();

**Comment by hanxiaofeng** [comment]
private void initTaskManager() {
        TaskManager.config()
                .enableFullLog(false)
                .setLogTracker(createTracker())
                .enableObjectReuse(true)
                .setDefaultTimeOut(3000000)
                .enableMemoryCleanUp(true)
                .setIdleTaskOffset(100)
                .setThreadPoolStrategy(ITaskManagerConfig.STRATEGY_POOL_EXECUTOR)
                .initTaskManager(this);
        registerCallback();
    }

**Comment by Carlyle-Lee** [comment]
这是一个设计上的问题:

**Comment by Carlyle-Lee** [comment]
这是当前Idle Task 的实现造成的。Idle Task 区分两种模式：
1）运行在主线程的模式： 主线程需要由 主线程空闲时的idle Handler 触发。 2） 运行在子线程的模式。子线程下也需要在子线程任务数较小时触发。但是这个触发的检测是在线程池有任务运行完成后才执行的。（因此如果只提交一个idle task，idle task 并不会被立即执行）

如果想让这个Idle Task 较早执行，可以提交一些非 idle 的任务，就可触发。

**Comment by Carlyle-Lee** [comment]
Idle Task 一般是可延迟的任务，因此在设计上选择了由其他任务触发。 如果要立即执行参考其他立即executeSync  API

**Comment by hanxiaofeng** [comment]
谢谢 @Carlyle-Lee
